### PR TITLE
KMS-17117 update client libs

### PR DESCRIPTION
**Pull request by muli**

### CODE REVIEW

**Review by gonenradai — APPROVED** [review]
client is only used in the scope of migration.
if still supported by product - this is what QA should test

**Comment by muli** [comment]
Honestly, I am not sure that there's a real migration path from a pre-KAF Moodle version to any of the latest Moodle versions...

**Comment by gonenradai** [comment]
we haven't removed it, as far as I know.
are you referring to the entire process of first upgrading moodle and then our plugin? or you think there's no way in our plugin to initiate the process anymore?

**Comment by muli** [comment]
I meant the entire process, but now that you mentioned that customers should upgrade Moodle first and then our plugin, it might be needed after all.

**Pull request merged**
