### PR TITLE
KMS-19513 fixed function name

### PR DESCRIPTION
**Pull request by noychn-kaltura**

### CODE REVIEW

**Comment by muli** [comment]
Fadiha... How did I miss this? :(

**Comment by noychn-kaltura** [comment]
> Fadiha... How did I miss this? :(

**Comment by noychn-kaltura** [comment]
> Fadiha... How did I miss this? :(
How did **I** miss it? :( :(

**Review by muli — APPROVED** [review]

**Comment by omridevk** [comment]
> Fadiha... How did I miss this? :(

Easily.

**Pull request merged**
