### PR TITLE
SUP-7324_MOODLE_30 adding embedType param to regex when filtering emb…

### PR DESCRIPTION
**Pull request by omridevk**
…ed url

### CODE REVIEW

**Comment by omridevk** [comment]
Due to urgency I have added this patch to resolve the recent issue when old BSE is enabled.

**Comment by muli** [comment]
@omridevk, if you tested it and it works correctly, let me know and I will merge.

**Comment by omridevk** [comment]
@muli 

I have only tested for Moodle 30 actually.

**Comment by muli** [comment]
@omridevk - I find it hard to believe that anything will be different in previous versions.

**Comment by alon1980** [comment]
what about this -  if (14 == count($link) && $newurl == $kafuri) ? count have changed - doesnt that effects this section of code?

**Comment by omridevk** [comment]
@alon1980 

That is the reason I have used (:?), i.e non-capturing group. since we are not using it anyway it does not affect it anyway, and I am going to refactor this function entirely I thought it would be the easier approach here.

```
(?:embedType\/oldEmbed\/)?
```

(?:) everything inside the group will not be captured and will not  be added to the array of the preg replace.

Correct me if I am wrong here, but I thought the embedType/OldEmbed is only used for Blackboard and other places it does not matter. let me know if I am mistaken here.

**Comment by alon1980** [comment]
@omridevk  can you please comment what is the status of this ticket?

**Comment by omridevk** [comment]
@alon1980 
This can be merged, with a TODO that this part might need to be heavily refactor in the future.

**Comment by alon1980** [comment]
LGTM

**Pull request merged**
