### PR TITLE
Converting add_to_log to new logging system for Moodle 2.7+

### PR DESCRIPTION
**Pull request by ccle**
Moodle 2.7 introduced a new logging system and all calls to add_to_log() throw out deprecated warnings. This patch converts all the logging calls to the new system.

https://docs.moodle.org/dev/Logging_2

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @ccle,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by ccle** [comment]
I signed the agreement using my main Github account, @rlorenzo. The @ccle account is my organization's Github account.

**Comment by jessp01** [comment]
Hello @rlorenzo,

If the contribution is made on behalf of your company or organization, the cooperate version of the CLA doc must be signed.
I sent the document to the email address you provided when signing as @rlorenzo.
If you'd like, we can also create a DocuSign document for you to sign instead. If so, please let me know.

Thanks,

**Comment by rlorenzo** [comment]
Please close this pull request in favor of https://github.com/kaltura/moodle_plugin/pull/44

**Pull request closed without merging**
