### PR TITLE
SUP-6754 showing all users who are enrolled to the course

### PR DESCRIPTION
**Pull request by omridevk**

### CODE REVIEW

**Comment by muli** [comment]
@gonenradai - can you please take a look as well?

**Comment by gonenradai** [comment]
I'm missing a bit context.
It looks OK, but since I don't know what the underlying methods do it is a bit hard to say.

**Comment by omridevk** [comment]
@gonenradai 

Until now we have given the option to display all the students who are enrolled to the course regardless if they have submitted the assignment or not, event hough we offered that option, it had no effect of the display of the grade table.
This fix just apply the filter that we had already offered but did not work.
We show all the students that are enrolled, furthermore, we allow them to grade the student even if the student did not submit the assignment. I have copied this behaviour from Moodle normal assignment.

**Comment by amirlevykal** [comment]
@gonenradai 
Waiting for a go from you to merge this change
@muli I will merge 29_DEV and 30

**Comment by gonenradai** [comment]
OK then.

**Pull request merged**
