### PR TITLE
Place Media Gallery underneath active course in nav block

### LINKED ISSUE #137: Media Gallery shows in wrong place in Moodle 3
_originally filed here kaltura/moodle-local_kalturamediagallery#1_

Hi,
We're in the process of upgrading to Moodle 3.2 and noticed that the Media Gallery appears in the now-defunct "Current Course" section of the navigation block (we're using a Clean-theme based custom theme, and intend to do so for the foreseeable future).

selection_254

Instead the link should appear underneath with the currently active course within the "My courses" or "Courses" sections:

selection_253

selection_252

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #137

### CODE REVIEW

**Comment by cdipe** [comment]
Hi! How does this relate to this issue (please read until end of discussion) https://github.com/kaltura/moodle_plugin/issues/137

**Comment by stopfstedt** [comment]
@cdipe that patch contained in this PR changes the placement of the Kaltura Media Gallery link within the navigation block's hierarchy. Instead of attaching it to a (now-obsolete) "Current course" root node, it will find and attach it to the course node that's currently "active" on the page.

**Comment by cdipe** [comment]
I understand. But, that won't make anyone happy, since the currently active course ends up somewhere among the list of all courses a user have, as described here: https://tracker.moodle.org/browse/MDL-58213
Instead, all course information in the active course should be collected under Current course, as before. And according to Gavin Henricks at moodle.org the Kaltura plugin is causing the problem. He also showed me a moodle site without the kaltura plugin, and that was working fine.

**Comment by stopfstedt** [comment]
@cdipe "This won't make anyone happy" is a bit of a stretch - getting this fix in would at least make our team and me happier.
IMO, placing the media gallery underneath the currently active course is an improvement over the current situation, regardless where that course resides in the navigation tree.

As you pointed out, the nav block has a multitude of other usability issues. 
Most of which can be worked around with a bit of custom code. 
We are doing some gymnastics in an overridden block navigation renderer in order to emulate the former "Current course" functionality, feel free to check it out: https://github.com/ucsf-ckm/moodle-theme-ucsf/blob/master/classes/block_navigation_renderer.php
This can be done differently as well, e.g. by implementing the same hook as this locallib is doing. You got options.

**Comment by cdipe** [comment]
I apologize if I sounded arrogant. But, moodles whole idea to remove the admin option of closing My Courses as default in 3.2 is a mistake, since users - especially staff - tend to have loads of courses. To have that list open as default is extremely annoying. But, it can be closed as default with a javascript, as we have done. But, again, if the Current Course doesn't work as expected, that's not an option. As a Kaltura and Moodle user, I just want the navigation menu to work as expected.

**Comment by stopfstedt** [comment]
Good news! There's has been relevant activity in the Moodle tracker that may make this patch obsolete. 

https://tracker.moodle.org/browse/MDL-58213?focusedCommentId=466128&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-466128

**Comment by cdipe** [comment]
That sounds great!

**Comment by stopfstedt** [comment]
I'm closing this PR and associated ticket. The aforementioned [patch on M.O](https://tracker.moodle.org/browse/MDL-58213?focusedCommentId=466128&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-466128) is a superior to what i was working on, and makes my submission here obsolete.

**Pull request closed without merging**
