### PR TITLE
KMS-11337 send all standard lti params

### PR DESCRIPTION
**Pull request by muli**

### CODE REVIEW

**Comment by gonenradai** [comment]
Technically looks OK.
any reason not to just use the lti_build_standard_request method? are there stuff that the latter does which the former doesn't?

Note that this have to be done on any version 2.8+

**Comment by muli** [comment]
@gonenradai - yes.
I don't know why (the Moodle tracker wasn't much of a help either) but `lti_build_standard_request` does not do whatever `lti_build_request` does - for instance, add the roles, user ID, etc..

**Comment by gonenradai** [comment]
OK, so 
LGTM

**Comment by alon1980** [comment]
@gonenradai i am impressed by the level of LGTMs you find. are you sitting and paging through 10K pictures???????

**Comment by gonenradai** [comment]
no, I developed a special algorithm that finds a good one based on context of the previous comments in the discussion and text that the user already typed in the comment box.

LGTM

**Comment by muli** [comment]
Oh, this totally explains why you put a GIF of Khaleesi (Daenerys Targaryen in GoT) in a discussion about LTI params.

**Comment by gonenradai** [comment]
note that the acronyms are exactly the same:
khLeesi daenerys Targaryen In got ... LTI

**Comment by muli** [comment]
mind=blown

**Comment by alon1980** [comment]
i see Muli also developed something like that...

**Pull request merged**
