### PR TITLE
Add setting to enable fontawesome icons for navigation drawer

### PR DESCRIPTION
**Pull request by adpe**
Hi @muli 

Would be cool if you can add this additional setting. So users can choose which icons they want to use. Moodle core uses fontawesome in the navigation drawer and you're using images.

Greets,
Adrian

### CODE REVIEW

**Comment by adpe** [comment]
I've done a rebase and it should still work! Can you please have a look @noychn-kaltura?

**Comment by adpe** [comment]
Hi @muli 

Please look at this request, it's an easy one and will help a lot of people!

Greets,
Adrian

**Comment by noychn-kaltura** [comment]
@adpe thanks for your contribution and sorry for the long delay, we will consider your request with our product manager.

**Comment by adpe** [comment]
Hi @noychn-kaltura 

I just rebased again the branch look forward to integrating this in to your plugin. 

HTH,
Adrian

**Comment by adpe** [comment]
Push @noychn-kaltura 

Greets,
Adrian

**Comment by adpe** [comment]
Ping @muli @noychn-kaltura 

Can you please have a look to this PR? It's a pity that we provide working code and you don't pay attention.

Cheers,
Adrian

**Comment by muli** [comment]
Hi @adpe,

Thanks for this PR.

Based on what did you choose these specific icons for My Media and Media Gallery?
The My Media icon in particular seems unrelated ([This](https://github.com/moodle/moodle/blob/master/pix/t/go.png) is the image, right?).

Also, if we're letting admins to change the icons, wouldn't it make sense to let them choose somehow?

@idodido FYI.

Thanks,
Muli.

**Comment by adpe** [comment]
Hi @muli 

Please check the commit. You see, that the admin can choose to select what he wants and it should be self-explained what will be selected as icon. Is a Font Awesome icon from the Moodle core.

image

We already have this running over several months on our productive Moodle platforms.

Feel free to extend this configuration so that the user can provide a different `pix` or let them choose a custom Font Awesome icon.

Actual the user can not choose and is per default only a pix. This commit only provides a solution to change to simple Font Awesome icons.

image

Greets,
Adrian

**Comment by muli** [comment]
Yeah, I understand, it's just that the description in the settings page was not clear until you just clarified.

In any case, our Moodle's plugin Product Manager (@idodido) is the one who decides whether we will add this feature to our next release.

Thanks,
Muli.

**Comment by noychn-kaltura** [comment]
@adpe 
Thanks for your contribution to our plugin.
In this case, our product manager didn't approve this change.

Thanks,
Noy

**Comment by adpe** [comment]
Hi @noychn-kaltura and @muli 

It's a pity that this will not be merged. As the default behaivour is not changing and our code don't break things up. No it improves your integration!

So we'll keep our fork up-to-date (with our change!) and we will look how we will contribute in future to your plugins...

Greets,
Adrian

**Pull request closed without merging**
