### PR TITLE
Converting add_to_log to new logging system for Moodle 2.7+

### PR DESCRIPTION
**Pull request by rlorenzo**
Moodle 2.7 introduced a new logging system and all calls to add_to_log() throw out deprecated warnings. This patch converts all the logging calls to the new system.

https://docs.moodle.org/dev/Logging_2

This commit supersedes https://github.com/kaltura/moodle_plugin/pull/43

### CODE REVIEW

**Comment by gonenradai** [comment]
@rlorenzo Thank you for your contribution.
I started reviewing the changes and so far it looks good.

can I ask you to also create a similar PR against the MOODLE_28_DEV branch? so that this change will also apply on 2.8 and then going forward?

Note that we have have few changes already merged into the DEV branches, but not yet released as it is still pending QA allocation.
Most likely this pull request will also be merged prior to QA allocation, so will only be released once our QA will approve all those changes.

**Comment by rlorenzo** [comment]
@gonenradai Here is the commit for the 2.8 DEV branch: https://github.com/rlorenzo/moodle_plugin/commit/e63ed6781bba7e5d9e62ba07612b3c5d3dbaec8f

It wasn't a clean cherry-pick from the 2.7 branch.

In the future should pull requests be based off the dev branches?

**Comment by gonenradai** [comment]
@rlorenzo - yes, preferably they should be based on DEV branches, as those are the branches that are candidates to be next version.
I will take a look at the 2.8 PR and will merge them.
We should have QA allocation soon actually (couple of weeks) so this was a good timing :)

Thanks again for the contribution!

**Comment by gonenradai** [comment]
closing, as I created a PR to merge into MOODLE_27_DEV out of the same branch.

**Pull request closed without merging**
