### PR TITLE
Moodle 29 stable merge with dev

### PR DESCRIPTION
**Pull request by muli**

### CODE REVIEW

**Comment by gonenradai** [comment]
@muli please bump version number in all 3 dev branches (2.7, 2.8, 2.9)

**Comment by muli** [comment]
@gonenradai done. Can you please just make sure I did it correctly?

**Comment by gonenradai** [comment]
looks OK. you used the script, right?
do the same on the other versions.

**Comment by muli** [comment]
@gonenradai yes, used the script.
And I did the same to all other versions.

**Comment by gonenradai** [comment]
OK.

**Pull request merged**
